TrajectoryPlannerROS:
  max_vel_x: 1.3
  min_vel_x: 0.6

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

  acc_lim_x: 0.6
  acc_lim_theta: 1.0

  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15

  sim_time: 1.0

  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: false

