max_obstacle_height: 0.60 
obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.2,0.2], [-0.3,0.2], [-0.3,-0.2], [0.2,-0.2]]

inflation_radius: 0.4
map_type: costmap
origin_z: 0.0

observation_sources: laser_scan_sensor
laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 3}
