#Independent settings for the local planner's costmap
local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  map_type: costmap
  transform_tolerance: 0.5
  obstacle_range: 2.5
  max_obstacle_height: 2.0
  raytrace_range: 3.0
  cost_scaling_factor: 15.0
  lethal_cost_threshold: 100
  robot_radius: 0.2
  circumscribed_radius: 0.45
  inflation_radius: 0.65

  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: false
  rolling_window: true
  width: 3.0
  height: 5.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0

  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}